### ISSUE TITLE
Update pypi install to 0.3.0

### ISSUE THREAD

**Issue by ppizarror** [bcoconni/ValgrindCI#12]
Hi! Using the latest ``0.2.0`` version I caught the following issue:

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.1/x64/bin/valgrind-ci", line 23, in <module>
    main()
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/ValgrindCI/__init__.py", line 54, in main
    data.parse(args.xml_file)
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/ValgrindCI/parse.py", line 120, in parse
    self.errors.append(Error(error_tag))
                       ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/ValgrindCI/parse.py", line 50, in __init__
    for frame in tag.find("./stack[2]").findall("frame"):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'findall'
```

However, this has already been patched https://github.com/bcoconni/ValgrindCI/commit/e1bc53c18c7f71750b7dffd7280bb565480e236e. Thus.. can you update the pypi distribution to avoid this critical issue? Thanks!

**Comment by bcoconni** [comment]
ValgrindCI `0.3.0` has just been released.
Sorry for the long delay before processing your request.
